{"name": "Проверка получения ошибки при попытке авторизации под несуществующим пользователем", "status": "passed", "description": "Проверяем, что при попытке авторизации под несуществующим пользователем приходит ошибка, а также в ответе сервера получены верный код и тело.", "start": 1722541562959, "stop": 1722541563009, "uuid": "750de0d4-8ce7-43dd-af87-a94b3d251c5f", "historyId": "5dce0c5b5c8b164603d918d8b8b33202", "testCaseId": "5dce0c5b5c8b164603d918d8b8b33202", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_not_authorized_with_not_existent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-LJDD8TD"}, {"name": "thread", "value": "8712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}